### ISSUE TITLE
filtering=True doesn't work unconnected (no callback)

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-table#202]
filtering=True doesn't seem to be working in doc examples:

https://github.com/plotly/dash-docs/blob/master/tutorial/examples/table/interactivity_simple.py

![filter](https://user-images.githubusercontent.com/2789078/47888314-31c04400-de1a-11e8-9386-ebfaa7805e66.gif)

**Comment by notatallshaw** [comment]
This bug also for other options such as sorting, correct? I can not get the to work unless I connect then to a call back.

**Comment by kummerer94** [comment]
+1

I am having the same problem. I am just using the Quickstart example from the docs (https://dash.plot.ly/datatable) and am not able to sort or filter anything (it will not react to any input on my side).

**Comment by chriddyp** [comment]
Yup. For now, just connect it to a dummy callback (e.g. use the `data_timestamp` as an `Input`)

**Comment by chirayu11** [comment]
+1

**Comment by notatallshaw** [comment]
I can also reproduce this issue if the first callback raises PreventUpdate, e.g.:

```

if data is None:
    raise PreventUpdate

```

Even if the callback has a response after the first callback doesn't seem to matter anymore.

**Comment by Marc-Andre-Rivet** [comment]
The underlying issue seems to be https://github.com/plotly/dash-renderer/issues/98

**Comment by cldougl** [comment]
This has been fixed in version 3.1.8

**Comment by FrankGorringe** [comment]
Hi all. I am using dash=0.41.0, dash_table=3.6.0 and dash_renderer=0.22.0. I am copying exactly the first example from https://dash.plot.ly/datatable/interactivity. Filtering is not working for me (though sorting is working fine). If I understand correctly, both sorting and filtering should work here because the example contains a callback on a table property? If not, then please can someone provide a code example where filtering is working for them or any other clues to help me diagnose what's going wrong on my side? Many thanks and please let me know if you need any more info.

**Comment by gorrinfr** [comment]
I apologise, I was using the wrong syntax for filtering. I found this post (https://github.com/plotly/dash-table/issues/169#issuecomment-435242374) which explained the filtering syntax I'd need to use.

**Comment by davidalbertonogueira** [comment]
I'm using Dash 2.0.0 and this is still a problem. How to overcome? I created a dummy callback to the table and still doesn't work.
